sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  #firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- export PATH=$PWD/node_modules/.bin:$PATH
script:
- xvfb-run wct --skip-plugin sauce
