sudo: required
dist: trusty
language: node_js
node_js:
  - stable
branches:
  except:
    - gh-pages
addons:
  sauce_connect: true
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
script:
  - xvfb-run wct
env:
  global:
    - secure: >-
        VRXhNOY+u/emeiYza/tBJlSBykGpxae6SxWxKXZzQCTtYxIBLOkJiThQm7nwEIwKhF0meMDDtntbo11WGL8UxA1szyiFCcP1O4AglHSP6ASBWFlPnJGZZekyAFOHwvdXdNHaavHOwsVvLz7u6K1l5RcyYyqFkCmZTyqjBZowYTPeYYMMhAvyYJI7UqY7gbKir2uzWlX0XOoqNkCFc4ZX6tVhVEjvwuD9R/G4dSx+DDrY8AHh8BvRBg6yKIm2obCYOr6DRslX5QXxEQiKSrvyqRzC3BzSk8TDHjIcppkBIDk+CixZO26MjtwrVtENhuOguOJkWUzKDFhoR4vYKTdJ6OOSF/hj2P34ocsH4lnb7mjKVXWOQpbBtUh1oAKHvkzx+QM8N+yGiJ8ltV1UHIhRzERw9iDdJXtC0mrLR07xFArHqG0+xmq6ZCEVMwPGPctPWJ8GFMC/cCliEGaKlSZx8a8BahyXAvFS2hqLV/rr7VHHzk9IvzvEddo8Q8893y2tPFWqtavRbnAGIGR95p/jZmda3XUVlQldp3eYRIIlH7wlsM59Hds7qSRijGeCm0x701IjHSkbIzfdL2niZOkvB53Sxu0mWDmRh7ber9j+XnE38fvYuKEu4HxLJlI/S5z3y3p9tIQmAk178XYWJ6tMLpEtIhUxxmdfvjQJ80o1CIs=
    - secure: >-
        tUlKjP+sY4Jw2beqwFqpDa/+ilHtgOTzHTY39DJbeA+/wYaMOLsn5o4vks8axkvZt8NPLVlT5kWuFRa8r9ZMoFZhK0CntK5l6b3/flT8WOiO1R405XsvTA/or8PXgsakIH1Wsg4Rf27jZ8adzLPZDyQbj8SlKbyWLPbjiQDveNaVjgBH4Hfu0adHL465KDox9F1MRDeBf714LY6inGP4j4d9fbJi5RwPQD4G6mlG31ryNofqxyWYKYsQn87svU75EnMKdt8gfqi0Q1kAXTfUa3B4dYqu6BHgXKPwziwx0v/NmzLdw5dF7hqoVgt9kK5qa0uLh34xTzPCHFTiE9TFHdHhZx2gO4zobOYadg/uN1uUkIev9sw48TBx7xHF0z+O32TAMdGgSCiHzsduERbonISS7XzMdKOpuJYtYFHeVmoe1lp7z/Y53T39v4FtEa2JqoH1GC8lLkrUBRzytQsjeA1TN4ekcQhFWaIBsQKY84SYq0fh9lPe9XruUx8YXV8luq7WSkcMFWscsS6CVg1eR1sqla+LAXiXV+s1kRRpmnECBMXNlI0Sx9cgXNUtUkGlNWZL+YygD3t1Kwk+azJhTKbDB3tFjRBh68DiEpU9WtUoNkzTNgBfezGvbZIZNwgpXxAsbzPU/iZeDSc4JC4IMypDPnti6EpgcunqTYIGRho=
