sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: WIp3O7oaCmCboiF3pVmthlJEFCFCEf+1jHAG2TFDuZh50lVwrJXqNP9LuXMUTJK5OAn86R+QUg3kEhuTgjaVr0rbfnFmG38lJwpf8HKYNSsN2SG3M9mFcP2yiXN/Nit3PEVFi0HIOkRM/Viwq/zc+G6duGmelipPkh1sDm9NY+xb24dk2KZHC9mbz/Yhku5l6uQqS6/ylIZndvutZjmCiacwa4DDm3mHnY1Dwj2LY/phYmLbM5eXU0DWJDTD3ofenDRYZ8IhX/dZSA+3lj9Plp7cPqqj+7LV3stVwVDHytqnFJoNzhn3PyAq9xBhnofA1cEyOVDywPHcKYEf/nR0hULjpa3oA3+f34fgwZrgOESb5jkpru96rzFCdmcuaFo34qGySOkuvC/CjO4cWqaPcw8zpG/OwkVGb/3wls+y+3zdE00kGrzBmR/C4GLREFtG9tygXjD9z/fLvNEvl4us+RgeTBwFzlsYdTZ9eFlweNz9fOjv1C+7GBj6k2FDZ/KncgptYFsyjffB5NJai1BMtEcVxGEmSvkBzEHuvieEx/tzqTw/zf+zXQHi3Gnwuf7tRmLveX5xsdC4k/pOVIwPmgfxCQgBgL5FRNX3QU93Fp5esJG8M0hbmfyAB48eyXOHX6NKRVvxBKiEyfTZIVdB/2b5U8xN+fD+iRDw56LoZ0o=
  - secure: sdsLw/up/f0f/+bjanvLdEI/PGVY36fXCpY5YF5mJNX3en9r4lDCLnX9z5w818Oap+tHcBxGr8AfCi8hYhj9TffDyuuMzoqSsIe9Isf9caHKL9puOwFc+8X0ssBmjYt5AUtOpEqT0MC+cw/lZpg4ySNKnwym9O6ENh02lJj6eNY5CylgysCF38Zo78PwgNVq5AjipHCtAfaev6wgQiopxKzEThfJQFHg3Ujm0WCGkXkHSZ2fNDX9ok5vqVLConFlZIFCk7dDPmuCNfpt/dyxiHoYUEIEJ6phlC/nGV8k5zfDvvmhnDgn2V4J33sYI8dCy1npOn3I+EppGxu9AXO/dSeYmJXlrg94/YYPWj6rUn4b33Gq8kghtdpGiv0nIwp32bEWIjUtcqvNLdI0Zfm8o+U3DPCcuuqEnN9dOYi/5ThNAWvhASn9oTrAUP+k3CkDpdaqsUrOL/XciX7SUSJj++S8w68n5Vd25ip65JreLG7s3gE6s6aa0EWFadafyjMeY2lbc4zA6zLV+aY0JcIDV+ddtIGzoPZY5pP20Quzi4IkCn7mcYFlyiMp9HL9NKyy33yIb82zUpuFc15ZVRypQLHv2ycQCzEw3N4jenC+E0/ac2/meDErzo68Wv2IEzcsE0sHtuGiQLvnYgTE41IgTvfMddRP4jt4v7U9BNyYOgQ=
  - secure: XM5NQRrdK8sJNNZna+e0cvlU+fuYw4Ydm36x4hKh0CzLXxxdN+V7IqtfN6LNavPTWXuFT3e5G3+Pi0nuz1YSIqIrSr/bMpxocG60NbxuddWh4kgfEYH0I0pgoAh9eID2AVJ9bVAJfvMmLzsa5NFrQ+OKkqMuW5m495o8elpvg/eFKVJOgZMRyDNOtGQND5De6x8o1r0LO2JF9jnI1lqFiEKWp5UTjI+5Wse3ohf+wAM89ulESp+93IMtkiqL+Ip8++fxkIKEu2HsVajaEmQwAmUYdgvMg9NKpz4pxFgvEKphjqM+uxsB1+Wi2RJRAST6vtagYgleICw6fcw2Jn/KkrQN8l3tvi+SshInEcmMby79j4nKx7bx8aevsq+vhWLsFNir8u9CnVFXPOuYogYI3JS+vR9dOUsweBpPqQQZm8JwBuVmP5IntVt3huF+k0i7fN5DUnhzsdLgE7+rFkp55WsrbBBW2lP61I5Kdh2zsFH2NfTHf47zojc4CdWdxn3PcT6PxI2QQ14QCCn7mWEVTXsCtaohRnk8FlXbDt2BlACrkQQRyrm5lYKrAwDGwyWYe2v2vIb7jZmoSwPmkJ2W1xI4B23o1p0YIW+niXtlKarvjDXJUa4Q2QDH5lxPDMI9C4gTezuHML8GHxWxWf4khsD0/bBBgN9LdMNx8EBToyI=
  - secure: HlQAVedbTQmi4lp/BfKJzjHH1Q8HEKf3QM5kXCOfbEMXSFv+wKhA3WKWJoa68VC0lNy37E0PMhh0S3zXiN+vVndwb4CrWHRZRyFfcdCDumUwe6LERYoHo6sE8ORiZ8mhExMsrdq92JJW4JhExibXF1c+vbedVdXpMuxolfzyoY2tlfXEBnpaEm/IY/1b8IS4JVhFlsohzYnYHVXkExfDL8SZvg8QfKVDrpiLPpA8a5REZYidDINflbuD17O/tw2i+AfMa/LHG4izyw6j7kumxPLUBV3PD51ajKXKDmHdQ93lB0lWPGVAkTQo9AoHYCKWarJa/rOMhHwza/VXhGccvYRW+O8nbkUwEtFIabTubgldJ4vZF8tIdkJ72XTtutj69NXnTuuh3ldNrsHSZNkQHSxViYk7mzC3wQ37eIVR8mJfUlc3zwD+PMVHetMkC3hjtMotH9hoo6Z6mwqUNuEOOQSCX5gm+oZbk6IS6eU1lkU2AZEu7QFbFIqSEzNxxTjQLZZnzEYX/QnS9TUKPLyRylo+BX0bj4vXhxn/n7fwR/U4ce7zpv2sDWacf/mo2rkJd6sayVcQr1TrWIOMsBAzNvHW2ou796M4snshNNELtfnL4IY4MAUvXPkfvlNIjQnH6bszCvh5FTVfWWHpvzQzNV85FTxMRsRPw3gzVztqVGY=
